### ISSUE TITLE
possible bug getRandomValueFromInterval()

### ISSUE THREAD

**Issue by oryband** [cenkalti/backoff#18]
looking at [this line](https://github.com/cenkalti/backoff/blob/6c45d6bc1e78d94431dff8fc28a99f20bafa355a/exponential.go#L137), I think there can possibly be a case where the minimum interval can be negative, if `delta < minInterval`.

I tried solving it by changing that line to:
```go
import "math"
var minInterval = math.Min(0, float64(currentInterval)-delta)
```
but then the tests fail.

wdyt?

**Comment by cenkalti** [comment]
It does not solve it because math.Min does not have any effect when ```float64(currentInterval)-delta``` is negative. See http://play.golang.org/p/Fa9Spn7ZjE

In fact, RandomizationFactor must be a number between 0 and 1. I suggest putting some checks to fix invalid value. What do you think about https://github.com/cenkalti/backoff/commit/a37d51c220a01a267e7341d303a9b2630f280072 ?

**Comment by cenkalti** [comment]
@oryband ?

**Comment by oryband** [comment]
@cenkalti hey, sorry for the loooong delay. yes, this solution looks good, and actually solves the problem (in contrast to my faulty one). megre at will! feel free to close this issue once you do.

thanks for the tech support :)
