### ISSUE TITLE
context timeout via <-ctx.Done()

### ISSUE THREAD

**Issue by georgysavva** [cenkalti/backoff#95]
As I can understand from the code, Retry() function can be canceled via context timeout: [here](https://github.com/cenkalti/backoff/blob/e13aad97be0886358290fe5f1cce951f777c415d/retry.go#L71-L72)
And this check is inside the retry loop. But in case the actual `operation` is a long running operation or it can even block, the retry function won't be canceled after context timeout, because it will hang on operation for a long time. 
I think, that In order to achieve a strict cancelation we should listen for ctx.Done() in a separate gorutine outside of the retry loop.
Is it intentionally or not?

**Comment by georgysavva** [comment]
Also what one should use to restrict total time for retries? context timeout or `MaxElapsedTime`. As I can see they serve pretty similar purpose.
But for context you check the next interval, that it won't exceed the deadline: [here](https://github.com/cenkalti/backoff/blob/e13aad97be0886358290fe5f1cce951f777c415d/context.go#L62)
And you don't do the same for elapsedTime: [here](https://github.com/cenkalti/backoff/blob/e13aad97be0886358290fe5f1cce951f777c415d/exponential.go#L116-L122)

**Comment by cenkalti** [comment]
This is an old package and `Retry` function is created at a time when `context` package did not exists. That's why `Operation` function signature does not accept a `context.Context` parameter. If it blocks, it blocks and retrying can only be cancelled after it returns. For a strict cancellation, I recommend creating a separate `context.Context` with a timeout/deadline and pass to your blocking function and use `backoff.WithContext` function to wrap your `backoff.BackOff` instance. Please let me know if you need an example, I can write one.

I am going to update `ExponentionBackoff.NextBackOff` method to reflect the change you have asked. Can you please take a look. If it's okay I will tag the commit as new version.

**Comment by georgysavva** [comment]
Everything is clear, thanks. 
I saw the commit, it's exactly what I was asking for. Thank!

**Comment by cenkalti** [comment]
Tagged the commit as v4.0.2.
